### ISSUE TITLE
Grey Out Quebec

### ISSUE THREAD

**Issue by ymi023** [kevinkells/uottawa_immigration_sevice_provider_map#10]
Quebec information is not included in this data. Add following phrase to bottom right hand corner of map. 

"For Quebec Services, click here” (hyperlink “here” with website https://services.immigration-quebec.gouv.qc.ca/fr/partenaires/carte-partenaires/”)"

**Comment by kevinkells** [comment]
Added Quebec Data using mapping at https://docs.google.com/spreadsheets/d/1lWkiicLxNNwtDDEw7TFLCxrjGZr7EuZp/edit#gid=1130343910
