### ISSUE TITLE
Show popup on hover

### ISSUE THREAD

**Issue by ymi023** [kevinkells/uottawa_immigration_sevice_provider_map#7]
Information to include: address, phone, website, and email (if available)

**Comment by kevinkells** [comment]
The current implementation brings up the popup when clicking, and the popup remains until dismissing it. This permits the user to click on the URL in the popup.

If we implement this as a hover popup, when the user moves the mouse to click on the URL in the popup, the popup will disappear before the user can click on the URL.

**Comment by ymi023** [comment]
It is more important to allow the user to click on the URL. Issue closed.
